[build]
  command = "pnpm build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18"
  SECRETS_SCAN_ENABLED = "false"
  SECRETS_SCAN_OMIT_KEYS = "GMAIL_USER,GMAIL_APP_PASSWORD"

# Static files redirects
[[redirects]]
  from = "/logo.png"
  to = "/logo.png"
  status = 200

[[redirects]]
  from = "/favicon.ico"
  to = "/favicon.ico"
  status = 200

[[redirects]]
  from = "/profil/*"
  to = "/profil/:splat"
  status = 200

[[redirects]]
  from = "/world-explorer.png"
  to = "/world-explorer.png"
  status = 200

[[redirects]]
  from = "/yobo.png"
  to = "/yobo.png"
  status = 200

[[redirects]]
  from = "/*.png"
  to = "/:splat.png"
  status = 200

[[redirects]]
  from = "/*.jpg"
  to = "/:splat.jpg"
  status = 200

[[redirects]]
  from = "/*.jpeg"
  to = "/:splat.jpeg"
  status = 200

[[redirects]]
  from = "/*.svg"
  to = "/:splat.svg"
  status = 200

[[redirects]]
  from = "/*.pdf"
  to = "/:splat.pdf"
  status = 200

# SPA fallback - must be last
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/CV_Soufiane.pdf"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Content-Type = "application/pdf"
    Content-Disposition = "inline; filename=CV_Soufiane_HAJJI_2025.pdf"

[[headers]]
  for = "/logo.png"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"